node {

    env.AWS_ECR_LOGIN=true
    def newApp
    def registry = 'karimamch/dockerjenkins'
    def registryCredential = 'karimamch'

        stage('Git') {
		git 'https://github.com/KaMech/Jenkins.git'
	        }
       
        stage('build') {
               
                sh 'python --version'
		
                sh 'echo $PATH; pip install Flask'
	}   
        
        stage('test') {
           
                sh 'python app.py'
            
        }

        stage('Building image') {
        docker.withRegistry( 'https://' + registry, registryCredential ) {
		    def buildName = registry + ":$BUILD_NUMBER"
			newApp = docker.build buildName
			newApp.push()
            }
	    }
	stage('Registring image') {
        docker.withRegistry( 'https://' + registry, registryCredential ) {
    		newApp.push 'latest2'
            }
	    }

        stage('Removing image') {
        sh "docker rmi $registry:$BUILD_NUMBER"
        sh "docker rmi $registry:latest"
        }





    
}
